config/routes.rb
Rails.application.routes.draw do

  resources :workout_logs

  devise_for :users
  resources :users
  resources :workouts
  resources :workout_activities

  resources :entries
  resources :activities

  root :to => "pages#home"

  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :activities, through: :workout_activities
  has_many :workout_activities, :inverse_of => :workout
  accepts_nested_attributes_for :workout_activities, :reject_if => lambda { |b| b[:activity_id].blank? }
  validates :workout_name, presence: true
  has_many :workout_logs

  def getWorkoutActivities
  	WorkoutActivity.where(workout_id: self.id)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  # scope_to :current_user

  # GET /workouts
  # GET /workouts.json
  def index
    # @workouts = Workout.current_user.all
    # @workouts = Workout.where(user: => current_user).all
    @workouts = Workout.where(user_id: current_user).all
    # @workouts = current_user.workouts
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @activities = Activity.all
  end

  # GET /workouts/new
  def new
    @workout = Workout.where(user_id: current_user).new

    @workout.workout_activities.new
    # @workout.activities.build # create a new activity on the workout
  end


  # def create
  #   @workout = Workout.new(params[:workout])
  #   @activity = @workout.activities.build(params[:activity])
  #   if @workout.save
  #     redirect_to :action => 'index'
  #   else
  #     render :action => 'new'
  #   end
  # end

  # GET /workouts/1/edit
  def edit
  end

  # def duplicate
  #   @workout = Workout.clone
  #   @workout.save
  # end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.where(user_id: current_user).new(workout_params)
    # binding.pry
    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_name: workout_params[:workout_name], notes: workout_params[:notes], focus: workout_params[:focus])
        @workout.workout_activities.each_with_index do |activity, index|
          @workout.workout_activities[index].update(workout_params[:workout_activities_attributes][index.to_s])
        end 
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.where(user_id: current_user).destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:workout_name, :notes, :workout_activities_attributes => [ :sets, :reps, :weight, :distance, :time, :activity_id])
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout, :class => 'form') do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workout_name, "Name your Workout", :class => 'h1' %><br>
    <%= f.text_field :workout_name %>
  </div>

  <div class="field">
    <%= f.label :focus, "Workout Focus" %>
    <%= f.text_field :focus %>
  </div>

  <!-- TODO: If workout activities doesn't exist add link add an activity -->
  <%= f.fields_for :workout_activities do |fwa| %>
    <div class="form-section" id="activity-<%= fwa.index %>">
      <div class="field">
        <%= fwa.label :name, "Activity Name" %><br>
        <div class="form-select">
          <%= fwa.select(:activity_id, Activity.all.collect { |a| [a.name, a.id]}, include_blank: true) %>
        </div>
      </div>

      <div class="field" id="workout_sets">
        <%= fwa.label :sets, "Sets" %>
        <%= fwa.text_field :sets %>
      </div>

      <div class="field" id="workout_reps">
        <%= fwa.label :reps, "Reps" %>
        <%= fwa.text_field :reps %>
      </div>
      <div class="field" id="workout_weight">
        <%= fwa.label :weight, "Weight (lbs)" %>
        <%= fwa.text_field :weight %>
      </div>
      <div class="field" id="workout_distance">
        <%= fwa.label :distance, "Distance (km)" %>
        <%= fwa.text_field :distance %>
      </div>
      <div class="field" id="workout_time">
        <%= fwa.label :time, "Time (minutes)" %>
        <%= fwa.text_field :time %>
      </div>
    </div>
  <% end %>

  <a href="javascript:void(0);" class="btn btn-collapse" id="new-activity-link">Add an activity to your workout
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="18 53.5 893 893" enable-background="new 18 53.5 893 893" xml:space="preserve">
    <path d="M464.5,53.5c123,0,228.167,43.667,315.5,131S911,377,911,500s-43.667,228.167-131,315.5s-192.5,131-315.5,131
      s-228.167-43.667-315.5-131S18,623,18,500s43.667-228.167,131-315.5S341.5,53.5,464.5,53.5z M688,555.5v-112H521v-167H409v167H241
      v112h168v168h112v-168H688z"/>
    </svg>
  </a>


  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :rows => '10' %>
  </div>
  <div class="actions">
  <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

<script>
$(document).ready(function(){
  var activityNum = 1;

  function addNewActivity(){
    var newActivity = "<div class='form-section' id='activity-"+ activityNum +"'>" + jQuery("#activity-0").html() + "</div>";
    var patternOne = /_0_/gi;
    var patternTwo = /[0]/gi;
    newActivity = newActivity.replace(patternOne, "_" + activityNum + "_");
    newActivity = newActivity.replace(patternTwo, activityNum);
    console.log(newActivity);

    activityNum++;
    $('.form-section').after(newActivity);
  };

  $("#new-activity-link").click(function(){
    addNewActivity();
  });
});

</script>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>


<h2>You're doing great work <%= current_user.first_name %>! Keep it up.</h2>

<h1>Workout Listing</h1>

<table>
  <thead>
    <tr>
      <th>Workout Name</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <% if workout.user_id == current_user.id %>
        <tr>
          <td><%= workout.workout_name %>
          <td><%= workout.notes %></td>
            <td>
              <% workout.workout_activities.each do |wa| %>
                <%= wa.name %><br>
              <% end %>
            <td>
          </td>
          <td class="hidden-xs"><%= link_to 'Details', workout %></td>
          <td class="hidden-xs"><%= link_to 'Edit', edit_workout_path(workout) %></td>
          <td class="hidden-xs"><%= link_to 'Remove', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a New Workout', new_workout_path, :class => 'btn btn-default' %>

app/views/workouts/new.html.erb
<%= link_to 'Go Back', workouts_path, class: 'btn btn-right' %>


<div class="form">
  <h2>You're killing it <%= current_user.first_name %>! Keep up the great work!</h2>
  <h2>Create a New Workout</h2>
  <%= render 'form' %>
</div>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Workout name:
  <%= @workout.workout_name %>
</h1>

<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>Sets</th>
      <th>Reps</th>
      <th>Weight (lbs)</th>
      <th>Distance (km)</th>
      <th>Time (minutes)</th>
      <th>Edit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workout.getWorkoutActivities.each do |workout_activity| %>
      <tr>
        <td><%= workout_activity.getActivityName %></td>
        <% if workout_activity.sets %>
	        <td><%= workout_activity.sets %></td>
        <% else %>
        	<td class="no-data">N/A</td>
        <% end %>

        <% if workout_activity.reps %>
	        <td><%= workout_activity.reps %></td>
        <% else %>
        	<td class="no-data">N/A</td>
        <% end %>

        <% if workout_activity.weight %>
        	<td class="data"><%= workout_activity.weight %></td>
        <% else %>
        	<td class="no-data">N/A</td>
        <% end %>

        <% if workout_activity.distance %>
        	<td class="data"><%= workout_activity.distance %></td>
        <% else %>
        	<td class="no-data">N/A</td>
        <% end %>

        <% if workout_activity.time %>
        	<td class="data"><%= workout_activity.time %></td>
        <% else %>
        	<td class="no-data">N/A</td>
        <% end %>

        <td><%= link_to "Edit", edit_workout_path(@workout) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>
  Notes:
</h2>
<p>
  <%= @workout.notes %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout), :class => 'btn' %>
<%= link_to 'Back', workouts_path, :class => 'btn' %>
<%= link_to 'Add another activity to this workout', new_workout_activity_path(workout_id: @workout.id), :class => 'btn btn-default' %>
<!-- The above line passes in the id of the current workout as workout_id to the next page (meaning the workout_activities#new_form) -->
<!-- TODO: fix above path (nested routing?) to link to something like workout_activity/workoutId/new -->