config/routes.rb
Rails.application.routes.draw do

  resources :workout_logs

  devise_for :users
  resources :users
  resources :workouts
  resources :workout_activities

  resources :entries
  resources :activities

  root :to => "pages#home"

  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'

end

app/models/workout_log.rb
class WorkoutLog < ActiveRecord::Base
	belongs_to :workout
	belongs_to :user
end

app/controllers/workout_logs_controller.rb
class WorkoutLogsController < ApplicationController
  before_action :set_workout_log, only: [:show, :edit, :update, :destroy]

  # GET /workout_logs
  # GET /workout_logs.json
  def index
    if WorkoutLog.where(user_id: current_user)
      @workout_logs = WorkoutLog.where(user_id: current_user).all
    end
  end

  # GET /workout_logs/1
  # GET /workout_logs/1.json
  def show
  end

  # GET /workout_logs/new
  def new
    @workout_log = WorkoutLog.new(user_id: current_user.id)
    @workouts = Workout.all
  end

  # GET /workout_logs/1/edit
  def edit
    @workouts = WorkoutLog.where(user_id: current_user.id).all
    # raise 'hell'
  end

  # POST /workout_logs
  # POST /workout_logs.json
  def create
    @workout_log = WorkoutLog.new(workout_id: params[:workout_log][:workout_id], user_id: current_user.id)

    respond_to do |format|
      if @workout_log.save
        format.html { redirect_to @workout_log, notice: "Great! We've logged your workout for you!" }
        format.json { render :show, status: :created, location: @workout_log }
      else
        format.html { render :new }
        format.json { render json: @workout_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_logs/1
  # PATCH/PUT /workout_logs/1.json
  def update
    respond_to do |format|
      if @workout_log.update(workout_log_params)
        format.html { redirect_to @workout_log, notice: 'Workout log was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_log }
      else
        format.html { render :edit }
        format.json { render json: @workout_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_logs/1
  # DELETE /workout_logs/1.json
  def destroy
    @workout_log.destroy
    respond_to do |format|
      format.html { redirect_to workout_logs_url, notice: 'Workout log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_log
      @workout_log = WorkoutLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_log_params
      params[:workout_log]
    end
end

app/helpers/workout_logs_helper.rb
module WorkoutLogsHelper
end

app/views/workout_logs/_form.html.erb
<%= form_for(@workout_log) do |f| %>
  <% if @workout_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_log.errors.count, "error") %> prohibited this workout_log from being saved:</h2>

      <ul>
      <% @workout_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workout_id %>
    <div class="form-select">
      <select name="workout_log[workout_id]" id="workout_log_workout_id">
      <% @workouts.each do |workout| %>
        <option value="<%= workout.id %>"><%= workout.workout_name %></option>
      <% end %>
      </select>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/workout_logs/edit.html.erb
<h1>Editing Workout Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_log %> |
<%= link_to 'Back', workout_logs_path %>

app/views/workout_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workout Logs</h1>

<% if @workout_logs.length > 0 %>
  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @workout_logs.each do |workout_log| %>
        <tr>
          <td><%= workout_log.updated_at.strftime("%b %d, %Y") %></td>
          <td><%= workout_log.workout.workout_name %></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td><%= link_to 'Remove', workout_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-show">Sorry, nothing to show here yet.</div>
<% end %>
<br>

<%= link_to 'New Workout log', new_workout_log_path, :class => 'btn btn-default' %>

app/views/workout_logs/new.html.erb
<h1>New Workout Log</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_logs_path %>

app/views/workout_logs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_workout_log_path(@workout_log) %> |
<%= link_to 'Back', workout_logs_path %>