config/routes.rb
Rails.application.routes.draw do

  resources :workout_logs

  devise_for :users
  resources :users
  resources :workouts
  resources :workout_activities

  resources :entries
  resources :activities

  root :to => "pages#home"

  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  # belongs_to :workout #each activity only belongs to one workout?

  has_many :workout_activities
  has_many :workouts, through: :workout_activities
  validates :name, presence: true, uniqueness: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  	@activities = Activity.all
  end

  def new
  	@activity = Activity.new
  end

  def create
  	@activity = Activity.new(activity_params)

  	if @activity.save
  		redirect_to '/activities'
  	else
  		render 'new'
  	end
  end

  def activity_params
  	params.require(:activity).permit(:name, :sets, :repetition, :other)
  end

  def edit
  	@activity = Activity.find(params[:id])
  	render 'new'
  end

  def update
  	@activity = Activity.find(params[:id])
  	@activity.update(activity_params)
  	redirect_to '/activities'
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Activity Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :activity_type, "Activity Type", :class => 'field-label' %>
    <div class="form-select">
      <%= select_tag(
          "activity_type",
          options_for_select([
            ['Aerobic', 'aerobic'],
            ['Interval', 'interval'],
            ['Anaerobic', 'anaerobic'],
            ['Weights', 'weights'],
            ['Distance', 'distance'],
            ['Kettle Bells', 'kettle-bells']
          ]), include_blank: true
        ) %>
    </div>
  </div>

  <div class="actions">
   <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/activities/index.html.erb
<h1>Activity Listing</h1>

<table>
  <thead>
    <tr>
      <th>Activity Name</th>
      <th>Activity Type</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.activity_type %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to "Edit", edit_activity_path(activity) %></td>
        <td><%= link_to "Delete", activity_path(activity), method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
	<%= link_to "Add New Activity", new_activity_path, class: "btn btn-default", title: "Add New Activity" %>
</div>

app/views/activities/new.html.erb
<%= link_to "Back", activities_path, class: 'btn btn-right' %>

<div class="form">
  <h2>Hello, <%= current_user.first_name %></h2>
  <h1>Add a New activity</h1>
  <%= render 'form' %>
</div>

app/views/activities/show.html.erb
<h1>Activity</h1>
<p>Find me in app/views/activity/show.html.erb</p>

<!-- Add this for Devise -->
<p id="notice"><%= notice %></p>