config/routes.rb
Rails.application.routes.draw do

  resources :workout_logs

  devise_for :users
  resources :users
  resources :workouts
  resources :workout_activities

  resources :entries
  resources :activities

  root :to => "pages#home"

  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="sidebar">
    <p><% if user_signed_in? %>
        Logged in as <strong><%= current_user.first_name %></strong> <br>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <p class="copyright">FitJunkies &copy; 2015 <br>
      Designed & Developed By <%= link_to 'Robyn', "http://robynlarsen.ca/", target: '_blank' %> & <%= link_to 'Simon', "http://proudfeet.io/", target: '_blank' %> <br>
    </p>
  </div>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-62607125-1', 'auto');
    ga('send', 'pageview');

  </script>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>FitJunkies</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1, user-scalable=0">
  <link rel="shortcut icon" href="/assets/images/favicon.png">
  <link rel="apple-touch-icon" href="/assets/images/favicon.png">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="nav sidebar" role="navigation">
    <a href="<%= root_path %>" title="Fit Junkies" class="logo-junkie">F<span class="hidden-xs">it</span> J<span class="hidden-xs">unkies</span></a>
    <div class="navbar-header visible-xs">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <ul class="nav collapse" id="navbar-collapse">
      <li class=""><%= link_to "Workouts", workouts_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Workout Diary", workout_logs_path %></li>
        <li><%= link_to "New Activity", new_activity_path %></li>
        <li>
          <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
        </li>
        <li><%= link_to "Progress Diary", entries_path %></li>
        <!-- <li class="logged-in">Logged in as <strong><%= current_user.email %></strong></li> -->
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body class="body-background <%= params[:controller] %>-<%= params[:action] %>">

<div class="wrapper">
  <div class="inner-wrapper">
    <aside class="sidebar-container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/footer' %>
    </aside>

    <div class="content-wrapper">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body class="<%= params[:controller] %>-<%= params[:action] %>">

<div class="wrapper">
  <div class="inner-wrapper">
    <aside class="sidebar-container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/footer' %>
    </aside>

    <div class="home-wrapper">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>